server:
  port: 8089
web:
  upload-path: D:/yunyin/upload/
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloudview
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      file-size-threshold: 10MB
      enabled: true
      max-request-size: 100MB
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}

mybatis:
  mapper-locations: classpath:/mapper/*Dao.xml
  typeAliasesPackage: com.example.cloudviewserver.entity

